# fly.toml app configuration file generated for wildcat-roomie-api on 2023-05-16T18:46:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wildcat-roomie-api"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
